version: "3.8"
services:
    php-cli:
        build:
          context: backend/docker
          dockerfile: php-cli/Dockerfile
        environment:
           APPLICATION_ENVIRONMENT: dev
           APPLICATION_DEBUG: 1
        volumes:
           - ./:/yii2-start
    php-fpm:
        build:
          context: backend/docker
          dockerfile: php-fpm/Dockerfile
        environment:
          APPLICATION_ENVIRONMENT: dev
          APPLICATION_DEBUG: 1
        volumes:
          - ./:/yii2-start
    nginx:
        build:
          context: backend/docker
          dockerfile: nginx/Dockerfile
        ports:
          - "8080:8080"
        volumes:
          - ./:/yii2-start
        depends_on:
          - php-fpm